### ISSUE TITLE
Players who have op level 1 get to do BanHammer commands

### ISSUE THREAD

**Issue by DillonB07** [Patbox/BanHammer#1]
On my server I use [gnembon/fabric-carpet](https://github.com/gnembon/fabric-carpet).
I use the /player command. However, I don't like everyone using it so I set it so only people with op level 1 or higher could use it. Then I gave people op level 1 to use /player.
However, your mod says that these commands can be used by op level 1:
`/ban`
`/tempban`
`/ban-ip`
`/tempban-ip`
`/mute`
`/tempmute`
`/kick`
`/unban`
`/unban-ip`
`/unmute`
`/pardon`
Would it be possible to add a config option that changes the default op level?
So it could be set to 1, 2, 3 or 4.

**Comment by Patbox** [comment]
It's good feature request. I will add it soon!

**Comment by DillonB07** [comment]
Thank you!

**Comment by Patbox** [comment]
Added in 0.2.1: https://modrinth.com/mod/banhammer/version/LdvF3atc
