### ISSUE TITLE
Languages other than English are not supported

### ISSUE THREAD

**Issue by rantuhin** [Patbox/BanHammer#11]
The problem is both in the console and in the discord
![Image](https://user-images.githubusercontent.com/60667805/155853414-bf0b1930-bc98-4e23-a2cc-286c2fb70009.png)
![Image](https://user-images.githubusercontent.com/60667805/155853430-bad3702a-e4e6-4f64-9c8d-3627daf4da1f.png)

**Comment by Patbox** [comment]
Should be fixed in 0.5.0, please reopen if it's not the case
