### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BrymalHS** [Patbox/BanHammer#19]
This is an odd feature request, but since you already handled temp banning in this mod, do you think you can add an additional feature to handle death bans for a hardcore server? Ideally, I'd like the player to be banned on death, with the additional feature to count the deaths and increase the ban period for each death. You could make it configurable but what I need is 15 minutes for the first death and each death after to double the amount of time!

**Comment by Patbox** [comment]
Out of scope for this one. Thats something for some other mod
