### ISSUE TITLE
Carpet Mod incompatibility 

### ISSUE THREAD

**Issue by DillonB07** [Patbox/BanHammer#2]
Your mod is incompatible with [Carpet Mod](https://github.com/gnembon/fabric-carpet). In particular, the /player command. I am unable to get a log or test the other commands, but I thought that you would want to know.
Please could you try to fix it?
The player doesn't spawn and the console gives quite a few errors. Your mod is the issue as it worked fine without BanHammer. 
This is on a Fabric 1.16.5 multiplayer server.

**Comment by Patbox** [comment]
I will look into that

**Comment by DillonB07** [comment]
Sorry. I believe this was LuckPerms not your mod.

**Comment by Patbox** [comment]
Oh

**Comment by DillonB07** [comment]
Sorry.

**Comment by Patbox** [comment]
Could you share the logs here? It might help a little

**Comment by DillonB07** [comment]
`07.04 14:39:40 [Server] Server thread/ERROR Command exception: /player Alex spawn
07.04 14:39:40 [Server] INFO java.lang.NullPointerException: null
07.04 14:39:40 [Server] INFO at net.minecraft.class_3222.hasPermission(class_3222.java:4710) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at me.lucko.luckperms.fabric.listeners.PermissionCheckListener.onPlayerPermissionCheck(PermissionCheckListener.java:67) ~[LuckPerms-Fabric-5.3.9.jar:?]
07.04 14:39:40 [Server] INFO at me.lucko.luckperms.fabric.listeners.PermissionCheckListener.onPermissionCheck(PermissionCheckListener.java:60) ~[LuckPerms-Fabric-5.3.9.jar:?]
07.04 14:39:40 [Server] INFO at me.lucko.fabric.api.permissions.v0.Permissions.getPermissionValue(Permissions.java:53) ~[6d8f14ed-750b-4ea1-9966-82ec1b12f065.jar:?]
07.04 14:39:40 [Server] INFO at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:79) ~[6d8f14ed-750b-4ea1-9966-82ec1b12f065.jar:?]
07.04 14:39:40 [Server] INFO at me.lucko.fabric.api.permissions.v0.Permissions.lambda$require$2(Permissions.java:118) ~[6d8f14ed-750b-4ea1-9966-82ec1b12f065.jar:?]
07.04 14:39:40 [Server] INFO at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_2170.method_9239(class_2170.java:308) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_2170.method_9241(class_2170.java:302) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_3324.method_14596(class_3324.java:653) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_3324.method_14576(class_3324.java:553) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_3324.method_14570(class_3324.java:189) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at carpet.patches.EntityPlayerMPFake.createFake(EntityPlayerMPFake.java:48) ~[fabric-carpet-1.16.5-1.4.30+v210331.jar:?]
07.04 14:39:40 [Server] INFO at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:282) ~[fabric-carpet-1.16.5-1.4.30+v210331.jar:?]
07.04 14:39:40 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_2170.method_9249(class_2170.java:249) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_3244.method_14370(class_3244.java:1211) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_3244.method_31286(class_3244.java:1198) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_3244.method_12048(class_3244.java:1177) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_2797.method_12115(class_2797.java:36) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.handler$bag000$modifiedRunLoop(MinecraftServer.java:5319) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
07.04 14:39:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
07.04 14:39:40 [Multicraft] Alex[local] ran command Message of the Day`

**Comment by DillonB07** [comment]
Do you know other permissions mods?

**Comment by Patbox** [comment]
https://github.com/Gegy/player-roles Maybe, but it might be issue with https://github.com/lucko/fabric-permissions-api

**Comment by DillonB07** [comment]
I'll just do without permissions.

**Comment by DillonB07** [comment]
Thanks though and sorry again.

**Comment by Patbox** [comment]
No problem!

**Comment by DillonB07** [comment]
I'm afraid I have to reopen this issue.
LuckPerms fixed the incompatibility with Carpet Mod's /player and without your mod it works fine. With it it doesn't.

**Comment by Patbox** [comment]
I will look into that!

**Comment by Patbox** [comment]
Should be fixed in 0.2.2!

**Comment by ghost** [comment]
Thanks!
I look forward to using it on my server.
