### ISSUE TITLE
Cannot kick carpet mod shadow players

### ISSUE THREAD

**Issue by BirdLogics** [Patbox/BanHammer#25]
[Carpet mod](https://github.com/gnembon/fabric-carpet) has the ability to create bot players to afk for you. However, the BanHammer `/kick` command cannot kick these players. Without a way to access the vanilla `/kick` command, there is no way to get rid of an afking player without `/kill`, which will cause the player to loose their inventory.

Could a way to disable the BanHammer `/kick` command and enable the vanilla `/kick` command be added? I don't really need to log when players are kicked. Adding a setting is one solution, but making BanHammer's `/kick` work with carpet bots would be nice too.

**Comment by LostLuma** [comment]
> there is no way to get rid of an afking player without /kill, which will cause the player to loose their inventory.

Fwiw this is not true, the `/player <name> kill` command from carpet simply removes the fake player, and when they are respawned their inventory persists.

**Comment by Patbox** [comment]
Vanilla kick should be accessible under /minecraft:kick

**Comment by BirdLogics** [comment]
You're right, this appears to be a misunderstanding on my part. Thanks.
