### ISSUE TITLE
Add support for setting config values via Environment Variables

### ISSUE THREAD

**Issue by ChristopherHaws** [Patbox/BanHammer#27]
I like to keep all my config files in a git repo to easily see everything I have changed and rollback if needed. I currently dont commit the banhammer config file because it contains my SQL database credentials in it. I would like to be able to configure these values via a env variables. I use docker containers to compose my MC server which allows for passing env variables to the container.

Thanks!

**Comment by Patbox** [comment]
Added in 0.5.6 and 0.6.1
