### ISSUE TITLE
A Temp-Banned Player was able to log in and player for 2 hours.

### ISSUE THREAD

**Issue by TwoPointInfinity** [Patbox/BanHammer#28]
Thats just it everything in the title. A player was banned for a week, and then during their ban, the day after it was set in they logged in to check their ban it was lifted. After they played for 2 hours, while no staff were active, banhammer seemingly caught up and re-initiated the ban.

**Comment by TwoPointInfinity** [comment]
I can give more information if needed please let me know what you need

**Comment by Patbox** [comment]
What database you use and your mod version.

**Comment by TwoPointInfinity** [comment]
sqlite
banhammer-0.5.4+1.19.2

**Comment by TwoPointInfinity** [comment]
let me check my logs, but i banned them while they were offline, and they joined and played for 2 hours the morning the next day so that might be the next time they joined.

**Comment by TwoPointInfinity** [comment]
Yes, after banning them **while offline** they logged in just under 12 hours later. While playing they even relogged one time, kept playing and them it seems they tried to relog again and it did not let them re-connect. https://imgur.com/a/V8I9R66

**Comment by TwoPointInfinity** [comment]
Well i haven't had this issue again, i couldn't even tell you why it happened or how to reproduce it so i guess unless you find anything on this i would consider this issue kind of stale.

**Comment by Patbox** [comment]
Added some extra protection in 0.5.6 and 0.6.1, so it shouldn't happen again
