### ISSUE TITLE
[Feature Request] Tempban punishment format

### ISSUE THREAD

**Issue by TwoPointInfinity** [Patbox/BanHammer#29]
I seem to always want to ban someone for 1 week or 2 weeks and at the moment i don't notice i need to do days or months.
Would it be possible to add a unit of time to the expression for 1w
so even 1y5m2w1d would be possible?
This is of 0 importance really but i just find it odd not being able to do it and i even had to go to the mod page to see its not on the list of possible expressions.

**Comment by Patbox** [comment]
Added in 0.5.6 and 0.6.1
