### ISSUE TITLE
Banhammer can't connect to database when using dynmap

### ISSUE THREAD

**Issue by DaggeSme** [Patbox/BanHammer#5]
as the titel said when using dynmap the server crashes i have attached the log. The config is standard and when i remove dynmap the mod works
[latest.log](https://github.com/Patbox/BanHammer/files/6758222/latest.log)

**Comment by Patbox** [comment]
[bh.zip](https://github.com/Patbox/BanHammer/files/6758536/bh.zip)
Hey could you test this version?

**Comment by DaggeSme** [comment]
No still not woking it has added a new config file discrod-messages.json 
[latest.log](https://github.com/Patbox/BanHammer/files/6758571/latest.log)

**Comment by Patbox** [comment]
Yeah, it's unreleased version with discord webhook support. I planned to release it today, but I need to fix that issue first

**Comment by Patbox** [comment]
I will try to talk with dynmap devs to get the best solution
