### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by julianrendell** [Patbox/BanHammer#6]
Would it be possible to add MariaDB support?

I know very little about JDBC, but looking at https://mariadb.com/kb/en/about-mariadb-connector-j/ it looks like the MariaDB Driver can be used to access both mysql and MariaDB... maybe it's a drop in replacement for the mysql driver?

Would it be as simple as adding another class implementation in `BanHammer/src/main/java/eu/pb4/banhammer/database/` and adjusting the startup case statement in `BanHammer/src/main/java/eu/pb4/banhammer/BanHammerMod.java`?

and changing the build system dependencies?

thanks for considering this!

**Comment by Patbox** [comment]
From what I know mysql and mariadb are compatible so changing drivers shouldn't effect much. Unless you are getting errors with current one, then please either post them here or as new issue

**Comment by Patbox** [comment]
Most likely found the issue! It should be fixed in latest, just configure it like mysql database. I will keep it open until your responce

**Comment by Patbox** [comment]
No updates, so I guess it was resolved with other mysql fixes

**Comment by julianrendell** [comment]
@Patbox - thanks for looking into this; I've not had time to test this, and the kids who set up the server moved onto other things. But I suspect we'll be repeating the exercise again at some point, so I appreciate that it's likely to "just work" next time ;-).
